### PR TITLE
[RLP] Refactor integer decoding

### PR DESCRIPTION
**Pull request by weipin**
Hi, me again.

[ This PR isn't complete (more code and tests are left). While it's irresponsible to post something half-baked, I'd like to first confirm that this is indeed an issue and, if so, the direction of refactoring. ]

# Problem
When decoding RLP integers, the current implementation seems to allow leading zeroes. 
We probably should not, for the [RLP spec](https://ethereum.org/en/developers/docs/data-structures-and-encoding/rlp/) requires that "...positive RLP integers must be represented in big-endian binary form with no leading zeroes...".

Seems the current behavior is caused by not directly decoding integers through the underlying RLP lib --
we first decode RLP data to raw bytes and then convert the bytes to integers with custom code.

With a few quick tests, it seems possible to construct multiple different "enr:xxxx" and let the implementation parse them to one same node. Here is [an example](https://github.com/weipin/enr_ecdsa_nonce_generating/blob/main/examples/int_decoding.rs):
the three different "enr:xxxx" will be decoded as the same example node from the spec. 

The different "enr:xxxx" are constructed by [this script](https://github.com/weipin/py_enr_demo/blob/main/int_decoding.py). The script first decodes the RLP of the example node, replaces "seq" with bytes with leading zeros, and then reconstructs the RLP.

Wondering if this issue makes sense.

# Refactor
The code attached is a refactor attempt: it replaces the custom decoding code of `seq` with the method of the underlying RLP lib. 

Not sure about how to handle the rest (tcp4, tcp6, udp4, and udp6), for these are being decoded lazily, as far as I understand.

### CODE REVIEW

**Comment by AgeManning** [comment]
Hey, apologies for the late response, was attending devcon. 

Yes! We should definitely be relying more on the RLP library rather than the custom decoding here. I dont recall why I originally was converting to bytes initially. 

I'm happy to take this over and help with the additional changes. 

The decoding is very sensitive however. We'll probably have to run any changes through a bunch of fuzzers we have developed. If we introduce any kind of bug in this function it could be a serious problem for a number of dependent projects.

**Comment by weipin** [comment]
Hope you had a great conference. 

> I'm happy to take this over and help with the additional changes.

Better this way that you can take this over :) 
Was worried that too many changes would be involved when the decoding part is something fundamental.
Also the reason submitted an incomplete PR. Feel free to close the PR if it can make the refactor progress easier.

**Comment by dapplion** [comment]
I can take over the PR and complete. AFAIK the scope of the issue is:
- Ensure that on decode, if any RLP integer has leading zeros consider that payload invalid
- Add good unit test coverage
- Coordinate with the security team to fuzz

**Comment by dapplion** [comment]
After looking into it, is there any security issue with accepting to decode integers with leading zeros?

> With a few quick tests, it seems possible to construct multiple different "enr:xxxx" and let the implementation parse them to one same node

I don't understand the problem with that statement. You can create infinite ENRs for the same "node" where I assume is either the node address or the node's ID. Instead of prefix integers with zeros, just add random fields that are not used by other implementations.

In the context of Ethereum's beacon chain, the consequences of accepting an ENR that other implementations will reject are not severe. I have not though in depth on it, but the it not in the interest of the ENR publisher.

If the integers have to be checked for correctness then they must be decoded ahead of time. The getters like `tcp4` should not return de-serialization errors. That would require a significant refactor, please @AgeManning chip in your thoughts.

**Comment by weipin** [comment]
Appending few comments, if I may.

> I don't understand the problem with that statement. You can create infinite ENRs for the same "node" where I assume is either the node address or the node's ID. Instead of prefix integers with zeros, just add random fields that are not used by other implementations.

The statement had its context -- the data set is "fixed" (same key/value pairs). So in such a condition, there is supposed to have just one address, right?

The tests were created to merely help explain the problem, demonstrating that for the same pairs, besides the "formal" RLP representation, you can build others, and the implementation will accept. The tests can also be used to verify the issue against other implementations. I remember briefly verifying against a Python implementation. As soon as it returned an error for the leading zero ones, the PR was created.

Security issues aside (which I have no idea about), and priority aside, a fix for this could shoot two birds with one stone:
1. makes integer parsing respect the spec
2. simplifies the code by leveraging the underlying RLP lib

**Comment by AgeManning** [comment]
Yep, agreed with @weipin 

If we use the underlying RLP lib it handles it better for us. I dont think there's really that much security concern (apart from accidentally introducing bugs in the decoder). 

We should be more strict and follow the spec a bit closer. The RLP library allows us to do this. 

I've had this guy sitting here for a while because its a more nice-to-have rather than a critical change (apologies for the delay, its not forgotten tho).

**Comment by dapplion** [comment]
@AgeManning sounds reasonable. Then, what would you go for?
1. Decode lazily and change API to `pub fn tcp4(&self) -> Result<Option<u16>, _>`, returning Err on RLP decode error
2. Decode all known fields that might error ahead of time to keep the api as `pub fn tcp4(&self) -> Option<u16>`, and return Err only on decode fn
3. Decode lazily and in case of Err, return `None` with api `pub fn tcp4(&self) -> Option<u16>`

**Comment by AgeManning** [comment]
In think we should do 2). 

Currently the ENR crate will not permit anyone to create an invalid ENR. If they give us a base64 string, we cannot create an ENR if its junk or invalid in any way. 
Similarly we make it impossible for someone to build a corrupt ENR. 
Therefore, if you have an ENR type any where in your code, you are sure that it is to-spec and doesn't not have anything wrong with it, i.e invalid signature or bad rlp contents etc.

So I think we won't need to make any API changes at all for this modification.

**Comment by divagant-martian** [comment]
I'm a bit late to the discussion but it's actually possible to create a "corrupted" enr since we expose `insert` and `insert_raw_rlp`, which allow any key, included those reserved by the spec

**Comment by AgeManning** [comment]
> I'm a bit late to the discussion but it's actually possible to create a "corrupted" enr since we expose `insert` and `insert_raw_rlp`, which allow any key, included those reserved by the spec

That's a good point. We should check that the rlp data is legit in `insert_raw_rlp` and that we are not overwriting reserved keys from the spec.

**Comment by AgeManning** [comment]
I think this has been resolved in #21 

Can re-open if this is not the case.

**Pull request closed without merging**
