### PR TITLE
add signature to builder

### PR DESCRIPTION
**Pull request by divagant-martian**

### CODE REVIEW

**Comment by divagant-martian** [comment]
@mattsse  @leruaa In sight of signatures needing to be compatible across implementation since fields are ordered in the spec, I adapted what you guys wanted to do. Is this something you would be interested on?

**Comment by leruaa** [comment]
Thanks, indeed with this PR we will be able to build an `Enr` from a node record with an existing signature, and then serialize the `Enr` and persists it in db.

However, the reason in https://github.com/paradigmxyz/reth/issues/1384 to persist `Enr`s in db is to be able to add additionnal content like the announced fork id into the `Enr`, and I believe that if the `Enr` content is updated, a new signature has to be generated, and we can't do that because we don't have the PK.

Am I correct or did I miss something?

**Comment by AgeManning** [comment]
> Thanks, indeed with this PR we will be able to build an `Enr` from a node record with an existing signature, and then serialize the `Enr` and persists it in db.
> 
> However, the reason in [paradigmxyz/reth#1384](https://github.com/paradigmxyz/reth/issues/1384) to persist `ENR`s in db is to be able to add additionnal content like the announced fork id into the `Enr`, and I believe that if the `Enr` content is updated, a new signature has to be generated, and we can't do that because we don't have the PK.
> 
> Am I correct or did I miss something?

Yes you are correct. The point of an ENR is that it contains a bunch of fields that are signed by the original node-id (a signed record). So you can't add any field unless you are the original author (i.e have the private key corresponding to the node-id).

**Review by AgeManning — APPROVED** [review]
This looks good to me, if it has utility for others

**Comment by divagant-martian** [comment]
Closing since this won't solve the needs of reth and there is no need from other teams, happy to reopen if needed

**Pull request closed without merging**
