### PR TITLE
Thread safe ENR

### PR DESCRIPTION
**Pull request by emhane**
Exploring ways to make the `KBucketsTable` data structures apt for multiple overlapping overlays, I thought this might come in handy.

### CODE REVIEW

**Review by divagant-martian — COMMENTED** [review]
This is something you can achieve with `Deref` and `DerefMut`. I added a small example of how this looks like [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a9b828c230c9f793864bcd4b9fec1228) 

This, in any case, should be done by the library using the `Enr` object and not within the `enr` crate

**Comment by emhane** [comment]
Well the idea is not to change the API, which this way you link in playground does since `a_mut` must be called before being able to call `g` on `tsa` in main.

So even if the code is behind a feature deactivated by default, you think it shouldn't be shared along with the Enr type?

**Comment by AgeManning** [comment]
I see the merit in this approach. 

I think the Enr type is more like a standard primitive type. It's not thread safe, like most primitive types. In rust there are a number of ways to build thread-safe versions of primitive types. Usually I think the people building thread-safe types use wrapper structs and traits like you've done here but they exist in the project where they are needed. If we added it here, it constrains the type and way thread-safe things are handled (i.e have to use parking-lot and Arc<RwLock<>>). 

I think the struct and trait you have here is useful and should exist in the project where its used. In Lighthouse we also have struct that contain Enr's that must be threadsafe, but they are handled in Lighthouse. We could end up with multiple thread-safe implementations of Enr if we start including individual ones, I think. 

What do you think?

**Comment by emhane** [comment]
> I see the merit in this approach.
> 
> I think the Enr type is more like a standard primitive type. It's not thread safe, like most primitive types. In rust there are a number of ways to build thread-safe versions of primitive types. Usually I think the people building thread-safe types use wrapper structs and traits like you've done here but they exist in the project where they are needed. If we added it here, it constrains the type and way thread-safe things are handled (i.e have to use parking-lot and Arc<RwLock<>>).
> 
> I think the struct and trait you have here is useful and should exist in the project where its used. In Lighthouse we also have struct that contain Enr's that must be threadsafe, but they are handled in Lighthouse. We could end up with multiple thread-safe implementations of Enr if we start including individual ones, I think.
> 
> What do you think?

True, the lock library is limited to `parking_lot` for example. Yeah, I got the idea from Sean's `AsBlock` in lighthouse somewhere on the eip4844 branch :)

**Pull request closed without merging**
